# Swift CI Pipeline
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest-stable
    
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    # - name: Install Dependencies
    #   run: |
    #     swift package resolve

    # - name: Build
    #   run: |
    #     xcodebuild clean build -project Velocity.xcodeproj -scheme Velocity -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15'

    - name: Run Tests
      run: |
        xcodebuild test -project Velocity.xcodeproj -scheme Velocity -destination 'platform=iOS Simulator, OS=15.4, name=iPhone 14 Pro'


  # deploy:
  #   runs-on: macos-latest

  #   needs: build

  #   steps:
  #   - name: Deploy to App Store
  #     run: |
  #       # Add your deployment script here
  #       # Example: fastlane deliver
